[[main]]
none = "none"






[[main]]
name = "Recent Work"
pageRef = "recent_work"
identifier = "QQYKq6dVVM"
weight = 3




[[main]]
name = "CV"
url = "https://jonathantollefson.com/Tollefson_CV.pdf"
identifier = "sirRePSXc7"
weight = 6

[[footer]]
none = "none"
