[[main]]
none = "none"




[[main]]
name = "Research"
#pageRef = "research"
weight = 2


[[main]]
name = "Recent Work"
pageRef = "recent_work"
identifier = "QQYKq6dVVM"
weight = 3


[[main]]
name = "Environmental Roots of Urban Inequality"
pageRef = "cities_environments"
parent = "Research"
weight=1

[[main]]
name = "Community Resilience"
pageRef = "resilience"
parent = "Research"
weight=2

[[main]]
name = "Socio-Ecological City Project"
pageRef = "pvd"
parent = "Research"
weight=3

[[main]]
name = "Historical Geographies of Chicagoland"
pageRef = "chi"
parent = "Research"
weight=4


[[main]]
name = "Contested Knowledges"
pageRef = "contested_knowledges"
parent = "Research"
weight=5


[[main]]
name = "CV"
url = "https://jonathantollefson.com/Tollefson_CV.pdf"
identifier = "sirRePSXc7"
weight = 6

[[footer]]
none = "none"
