[[main]]
none = "none"


[[main]]
name = "Bio"
#pageRef = ""
weight = 1


[[main]]
name = "Research"
#pageRef = "research"
weight = 2


[[main]]
name = "Recent Work"
pageRef = "recent_work"
identifier = "QQYKq6dVVM"
weight = 3


[[main]]
name = "Environmental Roots of Urban Inequality"
pageRef = "cities_environments"
parent = "Research"
weight=1

[[main]]
name = "Community Resilience"
pageRef = "resilience"
parent = "Research"
weight=2

[[main]]
name = "Socio-Environmental Change in Cities"
pageRef = "pvd"
parent = "Research"
weight=3


[[main]]
name = "CV"
url = "https://jonathantollefson.com/Tollefson_CV.pdf"
identifier = "sirRePSXc7"
weight = 4

[[footer]]
none = "none"
